version: "2"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - mongo
      - postgres
  postgres:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=123456
      - TZ=GMT
    volumes:
      - "/usr/postgres:/var/lib/postgresql/data"
    ports:
      - 25432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "15050:80"
    networks:
      - postgres
    restart: unless-stopped
  mongo:
    image: 'mongo:3.4.1'
    volumes:
      - '/usr/mongo:/data/db'
    ports:
      - '27017:27017'
    networks:
      - mongo
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: